name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      # Enable Corepack and use project's specified Yarn version
      - run: corepack enable
      
      # Cache .yarn/cache for faster builds
      - name: Cache .yarn/cache
        uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install --immutable

      - uses: nrwl/nx-set-shas@v4

      # Ensure @nx/workspace is installed
      - run: yarn add @nx/workspace

      # Run affected commands
      - run: npx nx affected -t lint test build e2e-ci --verbose